DROP TABLE IF EXISTS stories;

CREATE TABLE stories (
    PRIMARY KEY (id),
    id INT GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(1024) NOT NULL,
    URL VARCHAR(512) NOT NULL,
    score SMALLINT NOT NULL DEFAULT 0 CHECK (score >= 0),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()::timestamp,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()::timestamp
);